plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_1:module_1_108"))
    implementation(project(":layer_1:module_1_125"))
    implementation(project(":layer_1:module_1_114"))
    implementation(project(":layer_1:module_1_129"))
    implementation(project(":layer_1:module_1_117"))
    implementation(project(":layer_1:module_1_126"))
    implementation(project(":layer_1:module_1_94"))
    implementation(project(":layer_1:module_1_123"))
    implementation(project(":layer_1:module_1_96"))
    implementation(project(":layer_1:module_1_124"))
    implementation(project(":layer_1:module_1_91"))
    implementation(project(":layer_1:module_1_93"))
    implementation(project(":layer_1:module_1_97"))
    implementation(project(":layer_1:module_1_104"))
    implementation(project(":layer_1:module_1_105"))
    implementation(project(":layer_1:module_1_102"))
    implementation(project(":layer_1:module_1_95"))
    implementation(project(":layer_1:module_1_100"))
    implementation(project(":layer_1:module_1_109"))
    implementation(project(":layer_1:module_1_121"))
    implementation(project(":layer_1:module_1_127"))
    implementation(project(":layer_1:module_1_103"))
    implementation(project(":layer_1:module_1_130"))
    implementation(project(":layer_1:module_1_122"))
    implementation(project(":layer_1:module_1_113"))
    implementation(project(":layer_1:module_1_106"))
    implementation(project(":layer_1:module_1_119"))
    implementation(project(":layer_1:module_1_132"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_101"))
    implementation(project(":layer_1:module_1_90"))
    implementation(project(":layer_1:module_1_92"))
    implementation(project(":layer_1:module_1_116"))
    implementation(project(":layer_1:module_1_112"))
    implementation(project(":layer_1:module_1_120"))
    implementation(project(":layer_1:module_1_107"))
    implementation(project(":layer_1:module_1_98"))
    implementation(project(":layer_1:module_1_128"))
}
        