plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_31"))
}
        