plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_58"))
}
        