plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_67"))
}
        