plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_79"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_26"))
}
        