plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_27"))
}
        