plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_86"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_81"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_32"))
}
        