plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_83"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_22"))
}
        