plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_77"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_73"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_87"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_34"))
}
        