plugins {
    id ("java-library")
    id ("maven-publish")
    id ("jacoco")
    id("awesome.kotlin.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_51"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_71"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_82"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_76"))
    implementation(project(":layer_0:module_0_88"))
    implementation(project(":layer_0:module_0_72"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_75"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_80"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_85"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_84"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_68"))
    implementation(project(":layer_0:module_0_78"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_74"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_9"))
}
        